---
  -name: playbook1
  hosts: surya_node1
  become: true
  tasks:
    -name: task_git
      yum:
        name: git
        state: latest
    -name: task_git service
      ansible.builtin.service:
        name: git
        state: started
  tasks:
    -name: task_jenkins
      yum:
        name: jenkins
        state: latest
    -name: task_jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
  tasks:
    -name: task_httpd
      yum:
        name: httpd
        state: latest
    -name: task_httpd service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes
    -name: creating html file
      ansible.builtin.file:
        path: /var/www/index.html   
        state: touch 
        




        
    


  







 